Feat/loss soft hkr
deel-ai/deel-lip pull request #86
Opened 2023-11-15 13:19 UTC by franckma31

Introduce the multiclass loss : MulticlassSoftHKR  defined in the paper "On the explainable properties of 1-Lipschitz Neural Networks: An Optimal Transport Perspective" Serrurier et al (Neurips'23) that combine an optimal transport loss with a softmax temperature coefficient (useful when the numer of classes is high like in Imagenet dataset)

2023-11-22 09:15 UTC, cofri requested changes

2024-02-02 16:11 UTC, franckma31 commented on tests/test_losses.py
> +
test_minibatches_multiclass_losses is not possible dur to the moving_mean computed on the batch. Each sub minibatch would have a different mean and leading a a different temperature for the softmax. In real condition all moving_mean may converge to the same value but unit test will fail

test_noreduction will be ok

2024-02-02 16:12 UTC, franckma31 commented on deel/lip/losses.py
> +        `deel.lip.utils.process_labels_for_multi_gpu()` function.
comment on multi-gpu removed

2024-02-15 11:15 UTC, franckma31 commented on deel/lip/losses.py
> +        self.temperature = temperature * self.min_margin_v
self.temperature remains constant during the training. The only variable is self.current_mean but the question of serialization of the value is good

2025-03-05 16:07 UTC, franckma31 commented on deel/lip/losses.py
> +            name="moving_mean",
changed to current_mean in 413640dbfb7ee699a03bce3323b6c882c1cb4ab8

2025-03-05 16:11 UTC, franckma31 commented on deel/lip/losses.py
> +            y_true = tf.where(y_true > 0, 1, -1)  # switch to +/-1
modification done in 691e74e0c22628a347ca218cbb79341bf2905273

2025-03-05 16:22 UTC, franckma31 commented on deel/lip/losses.py
> +            alpha_mean (float): geometric mean factor
done in 5d1d177b8f8ac2b93cc7742aa56a5c883d7aa6c4

2025-03-05 16:30 UTC, franckma31 commented on deel/lip/losses.py
> +        self.temperature = temperature * self.min_margin_v
resolved in 1b6205dda54d7fe9571b7617da9b9d4b04c65f87

2025-03-12 08:35 UTC, cofri approved these changes
👌

2025-03-12 08:37 UTC, merged